# Unit 23. 2D list

## 23.1 making and indexing 2D list

In [1]:
a = [[10, 20], [30, 40], [50, 60]]
a

[[10, 20], [30, 40], [50, 60]]

In [2]:
# a[row index][col index]
a[1][0]

30

In [4]:
a[1][-1] = 100
a

[[10, 20], [30, 100], [50, 60]]

In [13]:
import numpy as np 
b = np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
b[1,1] # more easy

5

In [8]:
b[1:-1,1:-1] # more easy so 2D list is not used and numpy and df is more used 

array([[ 5,  6],
       [ 9, 10]])

In [10]:
b[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [15]:
a = []
for i in range(4):
  t = []
  for j in range(4):
    t.append(4*i + j)
  a.append(t)
a

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [20]:
[[i*4+k for k in range(4)] for i in range(4)]

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [19]:
from pprint import pprint
pprint(a, indent=4, width=30)

[   [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]]


## 23.2 for loop use

In [21]:
for row in a:
  print(row)

[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]


In [27]:
for row in a:
  for el in row:
    print(f'{el:2d} ', end='')
  print()

 0  1  2  3 
 4  5  6  7 
 8  9 10 11 
12 13 14 15 


In [28]:
for w, x, y, z in a:  # list unpacking
  print(w, x, y, z)

0 1 2 3
4 5 6 7
8 9 10 11
12 13 14 15


## 23.3 create a list with loops 

In [30]:
a = [[0 for _ in range(2)] for _ in range(3)]
a

[[0, 0], [0, 0], [0, 0]]

In [31]:
a = [[0] * 2 for _ in range(3)]
a

[[0, 0], [0, 0], [0, 0]]

In [33]:
number = [3, 1, 3, 2, 5]

b = []
for i in number:
  line = []
  for _ in range(i):
    line.append(0)
  b.append(line)
b

[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]

In [34]:
[[0] * i for i in number]

[[0, 0, 0], [0], [0, 0, 0], [0, 0], [0, 0, 0, 0, 0]]

## 23.4 2D list assign and copy

In [35]:
a = [[10, 20], [30, 40]]
b = a
b[0][0] = 500
a

[[500, 20], [30, 40]]

In [36]:
a = [[10, 20], [30, 40]]
import copy
b = copy.deepcopy(a)
b[0][0] = 500
a

[[10, 20], [30, 40]]